# Generated by Django 3.1.2 on 2020-10-25 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('description_short', models.CharField(max_length=500, verbose_name='Короткое описание')),
                ('description_long', models.CharField(max_length=2000, verbose_name='Полное описание')),
                ('coordinates', models.JSONField(verbose_name='Координаты')),
            ],
        ),
    ]
