# Generated by Django 3.1.2 on 2020-10-26 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_image_number'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='image',
            unique_together={('place', 'number')},
        ),
    ]
